# https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[directory]
truncation_length = 10
truncate_to_repo = true

[git_status]
# WSL
windows_starship = '/mnt/c/Users/Pablo/scoop/apps/starship/current/starship.exe'
